### ISSUE TITLE
Allow configurable GET_EXT_IP_URL or other default providers

### ISSUE THREAD

**Issue by fOmey** [ludeeus/pycfdns#10]
Unfortunately ipifiy doesnt handle `X-Fowarded-For` headers very well.

Which means if your using any proxy tunneling, ipify detects the wrong IP address.

Funny enough I'm having issues while using cloudflare WARP, with an addon thats meant to be updating cloudflare records.. kinda funny. 

It's been a long term known issue with ipify: [#5](https://github.com/rdegges/ipify-api/issues/5), [#19](https://github.com/rdegges/ipify-api/issues/19)

In order to resolve the issue supposedly ipify is going to have to undertake a core redisgn which I doubt will happen anytime soon.

I hope by allowing a configurable `GET_EXT_IP_URL`, this will then trickle into the home assistant addon.. which will eventually solve my problem.

If this is way to much effort, I get it.. I'll just have to come up with another solution.

**Comment by ludeeus** [comment]
The ipify lookup will be removed in a future release of this package, and nothing will replace it, it's not really a job for this package to do that.
Just pass the external_ip to the update method.

https://github.com/ludeeus/pycfdns/blob/7d86ee30037202e2bbec8b818d799c68280ba359/pycfdns/__init__.py#L96
